packages:
  - 'admin-portal'
  - 'backend'
allowBuilds:
  '@parcel/watcher': true
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': true
  bcrypt: true
  prisma: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - puppeteer-core@25.11.0
